name: Build
on:
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  linux:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        otp-version: [24]
    runs-on: ${{ matrix.platform }}
    container:
      image: erlang:${{ matrix.otp-version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install cargo
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: Compile
      run: . $HOME/.cargo/env && make compile
    - name: Run Checks
      run: make check
    - name: Run Elvis
      run: make elvis
